services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    logging:
      driver: none

