name: Deployment pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: respotify.azurecr.io
        username: ${{ secrets.ACR_REGISTRY_USERNAME }}
        password: ${{ secrets.ACR_REGISTRY_PASSWORD }}

    - name: Build docker image
      run: docker build . -t respotify.azurecr.io/frontend

    - name: Deploy
      run: docker push respotify.azurecr.io/frontend

  restart-deployment:
    name: Restart service
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_CLUSTER_NAME }} --overwrite-existing

      - name: Restart deployment
        run: kubectl rollout restart deployment/frontend -n ingress-nginx
        continue-on-error: true #If aks cluster is not available, the pipeline should not fail
      
